# Generated by Django 4.2.5 on 2023-09-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_article_tag_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_info',
            field=models.TextField(max_length=700, null=True),
        ),
    ]
