# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180402_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('choices', models.CharField(choices=[('J', 'Jack'), ('P', 'Pes')], max_length=1)),
            ],
        ),
    ]
