# Generated by Django 4.2.5 on 2023-12-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='films')),
                ('title', models.CharField(max_length=60)),
                ('short_description', models.TextField(max_length=155)),
                ('description', models.TextField(max_length=990)),
                ('country', models.TextField(max_length=40)),
                ('running_time', models.IntegerField()),
            ],
        ),
    ]
