# Generated by Django 4.2.5 on 2023-12-06 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outcinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='photo',
        ),
        migrations.CreateModel(
            name='FilmPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='films')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='outcinema.film')),
            ],
        ),
    ]
