# Generated by Django 4.2.5 on 2023-12-07 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outcinema', '0002_remove_film_photo_filmphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='outcinema.film')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='slides', to='outcinema.homepageslider')),
            ],
        ),
        migrations.DeleteModel(
            name='FilmPhoto',
        ),
    ]
