# Generated by Django 4.2.5 on 2023-12-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcinema', '0004_film_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='start_date',
            field=models.DateField(default='2222-12-10'),
            preserve_default=False,
        ),
    ]
